### ISSUE TITLE
Problem to run in i386 Ubuntu 

### ISSUE THREAD

**Issue by roberto497** [ThalesIgnite/crypto11#99]
go version go1.16 linux/386

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3f8 pc=0x81435ad]

runtime stack:
runtime.throw(0x8183185, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x6a
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x23f

goroutine 1 [syscall]:
runtime.cgocall(0x8145a30, 0x8ce3ec4, 0x8160da0)
        /usr/local/go/src/runtime/cgocall.go:154 +0x67 fp=0x8ce3eb0 sp=0x8ce3e98 pc=0x804d8b7
github.com/miekg/pkcs11._Cfunc_New(0x8ad1420, 0x0)
        _cgo_gotypes.go:1246 +0x37 fp=0x8ce3ec4 sp=0x8ce3eb0 pc=0x8102ef7
github.com/miekg/pkcs11.New(0x818175d, 0x23, 0x0)
        /home/administrador/work/pkg/mod/github.com/miekg/pkcs11@v1.0.3-0.20190429190417-a667d056470f/pkcs11.go:787 +0x82 fp=0x8ce3ee4 sp=0x8ce3ec4 pc=0x8103bf2
github.com/ThalesIgnite/crypto11.Configure(0x8cb20c0, 0x0, 0x0, 0x0)
        /home/administrador/work/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:320 +0x12e fp=0x8ce3f68 sp=0x8ce3ee4 pc=0x813b23e
main.main()
        /home/administrador/GoLuksTeste/teste4.go:35 +0x98 fp=0x8ce3fc8 sp=0x8ce3f68 pc=0x8143078
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x253 fp=0x8ce3ff0 sp=0x8ce3fc8 pc=0x807cd63
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1315 +0x1 fp=0x8ce3ff4 sp=0x8ce3ff0 pc=0x80a7561
exit status 2

**Comment by Nicolas-Peiffer** [comment]
Hello, I am sorry I have no idea how to help you.

In 2026 the big project for crypto11 is to add the support of PKCS#11 v3.2 and the support of the ML-KEM PQC algorithm:

- https://github.com/eclipse-keypont/crypto11/pull/131
- We work on this branch mainly: [pkcs11-v3.2-ml-kem](https://github.com/eclipse-keypont/crypto11/tree/pkcs11-v3.2-ml-kem).
- It will lead to a crypto11@v2, as there are many changes, including we are using a new PKCS11 implementation [eclipse-keypont/pkcs11-go](https://github.com/eclipse-keypont/pkcs11-go).
- Summary of the changes here: [pkcs11-v3.2-ml-kem/CHANGELOG.md](https://github.com/eclipse-keypont/crypto11/blob/pkcs11-v3.2-ml-kem/CHANGELOG.md)

The other big project for 2026 is giving + moving the crypto11 project under the Eclipse Foundation.

Maybe `crypto11@v2` will solve your problem? Some v2 release candidates are already available and v2 will be shipped soonish.
